flow_dict = {
    ('18th (Pink Line)', 'Damen (Pink Line)'): 18103,
    ('18th (Pink Line)', 'Polk (Pink Line)'): 10917,
    ('35th-Bronzeville-IIT (Green Line)', 'Cermak-McCormick Place (Green Line)'): 12835,
    ('35th-Bronzeville-IIT (Green Line)', 'Indiana (Green Line)'): 27699,
    ('35th/Archer (Orange Line)', 'Ashland (Orange Line)'): 13679,
    ('35th/Archer (Orange Line)', 'Western (Orange Line)'): 48852,
    ('43rd (Green Line)', '47th (Green Line)'): 25831,
    ('43rd (Green Line)', 'Indiana (Green Line)'): 10291,
    ('47th (Green Line)', '43rd (Green Line)'): 9420,
    ('47th (Green Line)', '51st (Green Line)'): 24647,
    ('47th (Red Line)', 'Garfield (Red Line)'): 43458,
    ('47th (Red Line)', 'Sox-35th (Red Line)'): 30477,
    ('51st (Green Line)', '47th (Green Line)'): 8277,
    ('51st (Green Line)', 'Garfield (Green Line)'): 23499,
    ('54th/Cermak (Pink Line)', 'Cicero (Pink Line)'): 1811,
    ('63rd (Red Line)', '69th (Red Line)'): 43235,
    ('63rd (Red Line)', 'Garfield (Red Line)'): 24308,
    ('69th (Red Line)', '63rd (Red Line)'): 23318,
    ('69th (Red Line)', '79th (Red Line)'): 43032,
    ('79th (Red Line)', '69th (Red Line)'): 18536,
    ('79th (Red Line)', '87th (Red Line)'): 41107,
    ('87th (Red Line)', '79th (Red Line)'): 12497,
    ('87th (Red Line)', '95th/Dan Ryan (Red Line)'): 38949,
    ('95th/Dan Ryan (Red Line)', '87th (Red Line)'): 8547,
    ('Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)', 'Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)'): 258,
    ('Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)', 'Roosevelt (Red, Orange & Green Lines)'): 62955,
    ('Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)', 'Washington/Wabash (Brown, Green, Orange, Purple & Pink Lines)'): 72102,
    ('Addison (Blue Line)', 'Belmont (Blue Line)'): 21390,
    ('Addison (Blue Line)', 'Irving Park (Blue Line)'): 80799,
    ('Addison (Brown Line)', 'Irving Park (Brown Line)'): 17090,
    ('Addison (Brown Line)', 'Paulina (Brown Line)'): 19505,
    ('Addison (Red Line)', 'Belmont (Red, Brown & Purple Lines)'): 11034,
    ('Addison (Red Line)', 'Sheridan (Red Line)'): 2920,
    ('Argyle (Red Line)', 'Berwyn (Red Line)'): 10016,
    ('Argyle (Red Line)', 'Lawrence (Red Line)'): 23189,
    ('Armitage (Brown & Purple Lines)', 'Fullerton (Red, Brown & Purple Lines)'): 49860,
    ('Armitage (Brown & Purple Lines)', 'Sedgwick (Brown & Purple Lines)'): 91332,
    ('Ashland (Green & Pink Lines)', 'California (Green Line)'): 24952,
    ('Ashland (Green & Pink Lines)', 'Morgan (Green & Pink Lines)'): 34238,
    ('Ashland (Green & Pink Lines)', 'Polk (Pink Line)'): 22032,
    ('Ashland (Orange Line)', '35th/Archer (Orange Line)'): 50828,
    ('Ashland (Orange Line)', 'Halsted (Orange Line)'): 14886,
    ('Ashland/63rd (Green Line)', 'Halsted (Green Line)'): 1441,
    ('Austin (Blue Line)', 'Cicero (Blue Line)'): 7205,
    ('Austin (Blue Line)', 'Oak Park (Blue Line)'): 29495,
    ('Austin (Green Line)', 'Central (Green Line)'): 8220,
    ('Austin (Green Line)', 'Ridgeland (Green Line)'): 9058,
    ('Belmont (Blue Line)', 'Addison (Blue Line)'): 82295,
    ('Belmont (Blue Line)', 'Logan Square (Blue Line)'): 24677,
    ('Belmont (Red, Brown & Purple Lines)', 'Addison (Red Line)'): 3944,
    ('Belmont (Red, Brown & Purple Lines)', 'Fullerton (Red, Brown & Purple Lines)'): 78373,
    ('Belmont (Red, Brown & Purple Lines)', 'Southport (Brown Line)'): 22330,
    ('Belmont (Red, Brown & Purple Lines)', 'Wellington (Brown & Purple Lines)'): 1640,
    ('Belmont (Red, Brown & Purple Lines)', 'Wilson (Red & Purple Line)'): 40790,
    ('Berwyn (Red Line)', 'Argyle (Red Line)'): 21134,
    ('Berwyn (Red Line)', 'Bryn Mawr (Red Line)'): 9118,
    ('Bryn Mawr (Red Line)', 'Berwyn (Red Line)'): 18487,
    ('Bryn Mawr (Red Line)', 'Thorndale (Red Line)'): 8226,
    ('California (Blue Line)', 'Logan Square (Blue Line)'): 87656,
    ('California (Blue Line)', "Western (Blue Line - O'Hare Branch)"): 31369,
    ('California (Green Line)', 'Ashland (Green & Pink Lines)'): 20240,
    ('California (Green Line)', 'Kedzie (Green Line)'): 23138,
    ('California (Pink Line)', 'Kedzie (Pink Line)'): 14547,
    ('California (Pink Line)', 'Western (Pink Line)'): 7345,
    ('Central (Green Line)', 'Austin (Green Line)'): 11230,
    ('Central (Green Line)', 'Laramie (Green Line)'): 10421,
    ('Central (Purple Line)', 'Linden (Purple Line)'): 3967,
    ('Central (Purple Line)', 'Noyes (Purple Line)'): 1781,
    ('Central Park (Pink Line)', 'Kedzie (Pink Line)'): 5349,
    ('Central Park (Pink Line)', 'Pulaski (Pink Line)'): 10666,
    ('Cermak-Chinatown (Red Line)', 'Roosevelt (Red, Orange & Green Lines)'): 37757,
    ('Cermak-Chinatown (Red Line)', 'Sox-35th (Red Line)'): 45027,
    ('Cermak-McCormick Place (Green Line)', '35th-Bronzeville-IIT (Green Line)'): 29045,
    ('Cermak-McCormick Place (Green Line)', 'Roosevelt (Red, Orange & Green Lines)'): 16232,
    ('Chicago (Blue Line)', 'Division (Blue Line)'): 96082,
    ('Chicago (Blue Line)', 'Grand (Blue Line)'): 45976,
    ('Chicago (Brown & Purple Lines)', 'Merchandise Mart (Brown & Purple Lines)'): 94683,
    ('Chicago (Brown & Purple Lines)', 'Sedgwick (Brown & Purple Lines)'): 51158,
    ('Chicago (Red Line)', 'Clark/Division (Red Line)'): 14050,
    ('Chicago (Red Line)', 'Grand (Red Line)'): 20887,
    ('Cicero (Blue Line)', 'Austin (Blue Line)'): 31606,
    ('Cicero (Blue Line)', 'Pulaski (Blue Line)'): 8345,
    ('Cicero (Green Line)', 'Laramie (Green Line)'): 16521,
    ('Cicero (Green Line)', 'Pulaski (Green Line)'): 12887,
    ('Cicero (Pink Line)', '54th/Cermak (Pink Line)'): 5881,
    ('Cicero (Pink Line)', 'Kostner (Pink Line)'): 2909,
    ('Clark/Division (Red Line)', 'Chicago (Red Line)'): 12345,
    ('Clark/Division (Red Line)', 'North/Clybourn (Red Line)'): 12380,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'Clinton (Green & Pink Lines)'): 52753,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'Grand (Blue Line)'): 96919,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'Merchandise Mart (Brown & Purple Lines)'): 37532,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'State/Lake (Brown, Green, Orange, Pink & Purple Lines)'): 62198,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'Washington (Blue Line)'): 47081,
    ('Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)', 'Washington/Wells (Brown, Orange, Purple & Pink Lines)'): 5261,
    ('Clinton (Blue Line)', 'LaSalle (Blue Line)'): 27317,
    ('Clinton (Blue Line)', 'UIC-Halsted (Blue Line)'): 41131,
    ('Clinton (Green & Pink Lines)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 40850,
    ('Clinton (Green & Pink Lines)', 'Morgan (Green & Pink Lines)'): 48909,
    ('Conservatory (Green Line)', 'Kedzie (Green Line)'): 17998,
    ('Conservatory (Green Line)', 'Pulaski (Green Line)'): 20909,
    ('Cottage Grove (Green Line)', 'Halsted (Green Line)'): 9741,
    ('Cottage Grove (Green Line)', 'King Drive (Green Line)'): 5656,
    ('Cumberland (Blue Line)', "Harlem (Blue Line - O'Hare Branch)"): 10350,
    ('Cumberland (Blue Line)', 'Rosemont (Blue Line)'): 52608,
    ('Damen (Blue Line)', 'Division (Blue Line)'): 38027,
    ('Damen (Blue Line)', "Western (Blue Line - O'Hare Branch)"): 91814,
    ('Damen (Brown Line)', 'Montrose (Brown Line)'): 13533,
    ('Damen (Brown Line)', 'Western (Brown Line)'): 13136,
    ('Damen (Pink Line)', '18th (Pink Line)'): 9451,
    ('Damen (Pink Line)', 'Western (Pink Line)'): 16936,
    ('Davis (Purple Line)', 'Dempster (Purple Line)'): 6610,
    ('Davis (Purple Line)', 'Foster (Purple Line)'): 5949,
    ('Dempster (Purple Line)', 'Davis (Purple Line)'): 7839,
    ('Dempster (Purple Line)', 'Main (Purple Line)'): 7260,
    ('Dempster-Skokie  (Yellow Line)', 'Oakton-Skokie (Yellow Line)'): 3360,
    ('Diversey (Brown & Purple Lines)', 'Fullerton (Red, Brown & Purple Lines)'): 5690,
    ('Diversey (Brown & Purple Lines)', 'Wellington (Brown & Purple Lines)'): 2419,
    ('Division (Blue Line)', 'Chicago (Blue Line)'): 41720,
    ('Division (Blue Line)', 'Damen (Blue Line)'): 94384,
    ('Forest Park (Blue Line)', 'Harlem (Blue Line - Forest Park Branch)'): 3319,
    ('Foster (Purple Line)', 'Davis (Purple Line)'): 3188,
    ('Foster (Purple Line)', 'Noyes (Purple Line)'): 5006,
    ('Francisco (Brown Line)', 'Kedzie (Brown Line)'): 6766,
    ('Francisco (Brown Line)', 'Rockwell (Brown Line)'): 6791,
    ('Fullerton (Red, Brown & Purple Lines)', 'Armitage (Brown & Purple Lines)'): 89417,
    ('Fullerton (Red, Brown & Purple Lines)', 'Belmont (Red, Brown & Purple Lines)'): 56346,
    ('Fullerton (Red, Brown & Purple Lines)', 'Diversey (Brown & Purple Lines)'): 3978,
    ('Fullerton (Red, Brown & Purple Lines)', 'North/Clybourn (Red Line)'): 7294,
    ('Garfield (Green Line)', '51st (Green Line)'): 7339,
    ('Garfield (Green Line)', 'King Drive (Green Line)'): 23039,
    ('Garfield (Red Line)', '47th (Red Line)'): 27736,
    ('Garfield (Red Line)', '63rd (Red Line)'): 43409,
    ('Grand (Blue Line)', 'Chicago (Blue Line)'): 96176,
    ('Grand (Blue Line)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 47376,
    ('Grand (Red Line)', 'Chicago (Red Line)'): 18426,
    ('Grand (Red Line)', 'Lake (Red Line)'): 25226,
    ('Granville (Red Line)', 'Loyola (Red Line)'): 6941,
    ('Granville (Red Line)', 'Thorndale (Red Line)'): 12520,
    ('Halsted (Green Line)', 'Ashland/63rd (Green Line)'): 7971,
    ('Halsted (Green Line)', 'Cottage Grove (Green Line)'): 2270,
    ('Halsted (Orange Line)', 'Ashland (Orange Line)'): 52088,
    ('Halsted (Orange Line)', 'Roosevelt (Red, Orange & Green Lines)'): 16874,
    ('Harlem (Blue Line - Forest Park Branch)', 'Forest Park (Blue Line)'): 24291,
    ('Harlem (Blue Line - Forest Park Branch)', 'Oak Park (Blue Line)'): 4178,
    ("Harlem (Blue Line - O'Hare Branch)", 'Cumberland (Blue Line)'): 59088,
    ("Harlem (Blue Line - O'Hare Branch)", 'Jefferson Park (Blue Line)'): 11740,
    ('Harlem/Lake (Green Line)', 'Oak Park (Green Line)'): 3554,
    ('Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)', 'Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)'): 1957,
    ('Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)', 'LaSalle/Van Buren (Brown, Orange, Purple & Pink Lines)'): 20344,
    ('Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)', 'Roosevelt (Red, Orange & Green Lines)'): 33907,
    ('Harrison (Red Line)', 'Jackson (Red Line)'): 15008,
    ('Harrison (Red Line)', 'Roosevelt (Red, Orange & Green Lines)'): 57225,
    ('Howard (Red, Purple & Yellow Lines)', 'Jarvis (Red Line)'): 831,
    ('Howard (Red, Purple & Yellow Lines)', 'Oakton-Skokie (Yellow Line)'): 21324,
    ('Howard (Red, Purple & Yellow Lines)', 'South Boulevard (Purple Line)'): 12074,
    ('Howard (Red, Purple & Yellow Lines)', 'Wilson (Red & Purple Line)'): 17253,
    ('Illinois Medical District (Blue Line)', 'Racine (Blue Line)'): 18463,
    ('Illinois Medical District (Blue Line)', 'Western (Blue Line - Forest Park Branch)'): 35699,
    ('Indiana (Green Line)', '35th-Bronzeville-IIT (Green Line)'): 11063,
    ('Indiana (Green Line)', '43rd (Green Line)'): 26826,
    ('Irving Park (Blue Line)', 'Addison (Blue Line)'): 19665,
    ('Irving Park (Blue Line)', 'Montrose (Blue Line)'): 77987,
    ('Irving Park (Brown Line)', 'Addison (Brown Line)'): 17639,
    ('Irving Park (Brown Line)', 'Montrose (Brown Line)'): 15688,
    ('Jackson (Blue Line)', 'LaSalle (Blue Line)'): 44744,
    ('Jackson (Blue Line)', 'Monroe (Blue Line)'): 36490,
    ('Jackson (Red Line)', 'Harrison (Red Line)'): 54734,
    ('Jackson (Red Line)', 'Monroe (Red Line)'): 17245,
    ('Jarvis (Red Line)', 'Howard (Red, Purple & Yellow Lines)'): 3522,
    ('Jarvis (Red Line)', 'Morse (Red Line)'): 1972,
    ('Jefferson Park (Blue Line)', "Harlem (Blue Line - O'Hare Branch)"): 67037,
    ('Jefferson Park (Blue Line)', 'Montrose (Blue Line)'): 15556,
    ('Kedzie (Brown Line)', 'Francisco (Brown Line)'): 5572,
    ('Kedzie (Brown Line)', 'Kimball (Brown Line)'): 5521,
    ('Kedzie (Green Line)', 'California (Green Line)'): 19279,
    ('Kedzie (Green Line)', 'Conservatory (Green Line)'): 22102,
    ('Kedzie (Orange Line)', 'Pulaski (Orange Line)'): 39915,
    ('Kedzie (Orange Line)', 'Western (Orange Line)'): 10362,
    ('Kedzie (Pink Line)', 'California (Pink Line)'): 6175,
    ('Kedzie (Pink Line)', 'Central Park (Pink Line)'): 12722,
    ('Kedzie-Homan (Blue Line)', 'Pulaski (Blue Line)'): 33661,
    ('Kedzie-Homan (Blue Line)', 'Western (Blue Line - Forest Park Branch)'): 11969,
    ('Kimball (Brown Line)', 'Kedzie (Brown Line)'): 3799,
    ('King Drive (Green Line)', 'Cottage Grove (Green Line)'): 22382,
    ('King Drive (Green Line)', 'Garfield (Green Line)'): 6177,
    ('Kostner (Pink Line)', 'Cicero (Pink Line)'): 7710,
    ('Kostner (Pink Line)', 'Pulaski (Pink Line)'): 3299,
    ('LaSalle (Blue Line)', 'Clinton (Blue Line)'): 43916,
    ('LaSalle (Blue Line)', 'Jackson (Blue Line)'): 29680,
    ('LaSalle/Van Buren (Brown, Orange, Purple & Pink Lines)', 'Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)'): 32609,
    ('LaSalle/Van Buren (Brown, Orange, Purple & Pink Lines)', 'Quincy/Wells (Brown, Orange, Purple & Pink Lines)'): 21713,
    ('Lake (Red Line)', 'Grand (Red Line)'): 22474,
    ('Lake (Red Line)', 'Monroe (Red Line)'): 38316,
    ('Laramie (Green Line)', 'Central (Green Line)'): 13789,
    ('Laramie (Green Line)', 'Cicero (Green Line)'): 11648,
    ('Lawrence (Red Line)', 'Argyle (Red Line)'): 10616,
    ('Lawrence (Red Line)', 'Wilson (Red & Purple Line)'): 25811,
    ('Linden (Purple Line)', 'Central (Purple Line)'): 975,
    ('Logan Square (Blue Line)', 'Belmont (Blue Line)'): 84216,
    ('Logan Square (Blue Line)', 'California (Blue Line)'): 28588,
    ('Loyola (Red Line)', 'Granville (Red Line)'): 9496,
    ('Loyola (Red Line)', 'Morse (Red Line)'): 6358,
    ('Main (Purple Line)', 'Dempster (Purple Line)'): 8855,
    ('Main (Purple Line)', 'South Boulevard (Purple Line)'): 8219,
    ('Merchandise Mart (Brown & Purple Lines)', 'Chicago (Brown & Purple Lines)'): 52571,
    ('Merchandise Mart (Brown & Purple Lines)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 68101,
    ('Merchandise Mart (Brown & Purple Lines)', 'Washington/Wells (Brown, Orange, Purple & Pink Lines)'): 30585,
    ('Midway (Orange Line)', 'Pulaski (Orange Line)'): 6579,
    ('Monroe (Blue Line)', 'Jackson (Blue Line)'): 44691,
    ('Monroe (Blue Line)', 'Washington (Blue Line)'): 41619,
    ('Monroe (Red Line)', 'Jackson (Red Line)'): 45325,
    ('Monroe (Red Line)', 'Lake (Red Line)'): 18709,
    ('Montrose (Blue Line)', 'Irving Park (Blue Line)'): 16903,
    ('Montrose (Blue Line)', 'Jefferson Park (Blue Line)'): 73223,
    ('Montrose (Brown Line)', 'Damen (Brown Line)'): 14727,
    ('Montrose (Brown Line)', 'Irving Park (Brown Line)'): 15370,
    ('Morgan (Green & Pink Lines)', 'Ashland (Green & Pink Lines)'): 47095,
    ('Morgan (Green & Pink Lines)', 'Clinton (Green & Pink Lines)'): 37470,
    ('Morse (Red Line)', 'Jarvis (Red Line)'): 4218,
    ('Morse (Red Line)', 'Loyola (Red Line)'): 5244,
    ('North/Clybourn (Red Line)', 'Clark/Division (Red Line)'): 7604,
    ('North/Clybourn (Red Line)', 'Fullerton (Red, Brown & Purple Lines)'): 14933,
    ('Noyes (Purple Line)', 'Central (Purple Line)'): 4628,
    ('Noyes (Purple Line)', 'Foster (Purple Line)'): 2439,
    ("O'Hare (Blue Line)", 'Rosemont (Blue Line)'): 4795,
    ('Oak Park (Blue Line)', 'Austin (Blue Line)'): 5528,
    ('Oak Park (Blue Line)', 'Harlem (Blue Line - Forest Park Branch)'): 26467,
    ('Oak Park (Green Line)', 'Harlem/Lake (Green Line)'): 5361,
    ('Oak Park (Green Line)', 'Ridgeland (Green Line)'): 5129,
    ('Oakton-Skokie (Yellow Line)', 'Dempster-Skokie  (Yellow Line)'): 15549,
    ('Oakton-Skokie (Yellow Line)', 'Howard (Red, Purple & Yellow Lines)'): 5552,
    ('Paulina (Brown Line)', 'Addison (Brown Line)'): 18946,
    ('Paulina (Brown Line)', 'Southport (Brown Line)'): 21536,
    ('Polk (Pink Line)', '18th (Pink Line)'): 19642,
    ('Polk (Pink Line)', 'Ashland (Green & Pink Lines)'): 13793,
    ('Pulaski (Blue Line)', 'Cicero (Blue Line)'): 32702,
    ('Pulaski (Blue Line)', 'Kedzie-Homan (Blue Line)'): 10203,
    ('Pulaski (Green Line)', 'Cicero (Green Line)'): 18750,
    ('Pulaski (Green Line)', 'Conservatory (Green Line)'): 17194,
    ('Pulaski (Orange Line)', 'Kedzie (Orange Line)'): 7958,
    ('Pulaski (Orange Line)', 'Midway (Orange Line)'): 36595,
    ('Pulaski (Pink Line)', 'Central Park (Pink Line)'): 4347,
    ('Pulaski (Pink Line)', 'Kostner (Pink Line)'): 8794,
    ('Quincy/Wells (Brown, Orange, Purple & Pink Lines)', 'LaSalle/Van Buren (Brown, Orange, Purple & Pink Lines)'): 31715,
    ('Quincy/Wells (Brown, Orange, Purple & Pink Lines)', 'Washington/Wells (Brown, Orange, Purple & Pink Lines)'): 23428,
    ('Racine (Blue Line)', 'Illinois Medical District (Blue Line)'): 37082,
    ('Racine (Blue Line)', 'UIC-Halsted (Blue Line)'): 20330,
    ('Ridgeland (Green Line)', 'Austin (Green Line)'): 6352,
    ('Ridgeland (Green Line)', 'Oak Park (Green Line)'): 7266,
    ('Rockwell (Brown Line)', 'Francisco (Brown Line)'): 9263,
    ('Rockwell (Brown Line)', 'Western (Brown Line)'): 8243,
    ('Roosevelt (Red, Orange & Green Lines)', 'Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)'): 66441,
    ('Roosevelt (Red, Orange & Green Lines)', 'Cermak-Chinatown (Red Line)'): 45927,
    ('Roosevelt (Red, Orange & Green Lines)', 'Cermak-McCormick Place (Green Line)'): 31064,
    ('Roosevelt (Red, Orange & Green Lines)', 'Halsted (Orange Line)'): 54709,
    ('Roosevelt (Red, Orange & Green Lines)', 'Harold Washington Library-State/Van Buren (Brown, Orange, Purple & Pink Lines)'): 19370,
    ('Roosevelt (Red, Orange & Green Lines)', 'Harrison (Red Line)'): 15284,
    ('Rosemont (Blue Line)', 'Cumberland (Blue Line)'): 7621,
    ('Rosemont (Blue Line)', "O'Hare (Blue Line)"): 43619,
    ('Sedgwick (Brown & Purple Lines)', 'Armitage (Brown & Purple Lines)'): 49952,
    ('Sedgwick (Brown & Purple Lines)', 'Chicago (Brown & Purple Lines)'): 92616,
    ('Sheridan (Red Line)', 'Addison (Red Line)'): 4547,
    ('Sheridan (Red Line)', 'Wilson (Red & Purple Line)'): 1628,
    ('South Boulevard (Purple Line)', 'Howard (Red, Purple & Yellow Lines)'): 8803,
    ('South Boulevard (Purple Line)', 'Main (Purple Line)'): 9738,
    ('Southport (Brown Line)', 'Belmont (Red, Brown & Purple Lines)'): 24054,
    ('Southport (Brown Line)', 'Paulina (Brown Line)'): 20866,
    ('Sox-35th (Red Line)', '47th (Red Line)'): 44097,
    ('Sox-35th (Red Line)', 'Cermak-Chinatown (Red Line)'): 34770,
    ('State/Lake (Brown, Green, Orange, Pink & Purple Lines)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 75731,
    ('State/Lake (Brown, Green, Orange, Pink & Purple Lines)', 'Washington/Wabash (Brown, Green, Orange, Purple & Pink Lines)'): 64194,
    ('Thorndale (Red Line)', 'Bryn Mawr (Red Line)'): 14733,
    ('Thorndale (Red Line)', 'Granville (Red Line)'): 7521,
    ('UIC-Halsted (Blue Line)', 'Clinton (Blue Line)'): 24829,
    ('UIC-Halsted (Blue Line)', 'Racine (Blue Line)'): 39429,
    ('Washington (Blue Line)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 48757,
    ('Washington (Blue Line)', 'Monroe (Blue Line)'): 45860,
    ('Washington/Wabash (Brown, Green, Orange, Purple & Pink Lines)', 'Adams/Wabash (Brown, Green, Orange, Pink & Purple Lines)'): 61070,
    ('Washington/Wabash (Brown, Green, Orange, Purple & Pink Lines)', 'State/Lake (Brown, Green, Orange, Pink & Purple Lines)'): 71442,
    ('Washington/Wells (Brown, Orange, Purple & Pink Lines)', 'Clark/Lake (Blue, Brown, Green, Orange, Purple & Pink Lines)'): 6894,
    ('Washington/Wells (Brown, Orange, Purple & Pink Lines)', 'Merchandise Mart (Brown & Purple Lines)'): 16970,
    ('Washington/Wells (Brown, Orange, Purple & Pink Lines)', 'Quincy/Wells (Brown, Orange, Purple & Pink Lines)'): 32180,
    ('Wellington (Brown & Purple Lines)', 'Belmont (Red, Brown & Purple Lines)'): 1447,
    ('Wellington (Brown & Purple Lines)', 'Diversey (Brown & Purple Lines)'): 2989,
    ('Western (Blue Line - Forest Park Branch)', 'Illinois Medical District (Blue Line)'): 14959,
    ('Western (Blue Line - Forest Park Branch)', 'Kedzie-Homan (Blue Line)'): 34584,
    ("Western (Blue Line - O'Hare Branch)", 'California (Blue Line)'): 89858,
    ("Western (Blue Line - O'Hare Branch)", 'Damen (Blue Line)'): 34387,
    ('Western (Brown Line)', 'Damen (Brown Line)'): 11674,
    ('Western (Brown Line)', 'Rockwell (Brown Line)'): 11566,
    ('Western (Orange Line)', '35th/Archer (Orange Line)'): 11474,
    ('Western (Orange Line)', 'Kedzie (Orange Line)'): 44330,
    ('Western (Pink Line)', 'California (Pink Line)'): 16126,
    ('Western (Pink Line)', 'Damen (Pink Line)'): 8290,
    ('Wilson (Red & Purple Line)', 'Belmont (Red, Brown & Purple Lines)'): 45508,
    ('Wilson (Red & Purple Line)', 'Howard (Red, Purple & Yellow Lines)'): 29821,
    ('Wilson (Red & Purple Line)', 'Lawrence (Red Line)'): 11330,
    ('Wilson (Red & Purple Line)', 'Sheridan (Red Line)'): 583
}
